### Lab 3

Step 1 - Load Data

In [1]:
import numpy as np
import pandas as pd
	
df = pd.read_csv('spam.csv', encoding='latin-1', usecols=[0, 1], dtype=str) # specifying encoding is necessary because the data does not use UTF-8
df.columns = ['Labels', 'SMS']
	
df.head()

C:\Users\icha\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

Step 2 - Preprocessing

In [2]:
#Drop columns that are not used
df = df.drop(df.iloc[:,2:], axis=1)

# Check the data
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
	# Check the number of instances per class
	print(df['Labels'].value_counts())
	print('\n')
	
	# Check for completeness of data
	print(df.info())
	print('\n')
	
	# Check descriptive statistics
	print(df.describe())

v1
ham     4825
spam     747
Name: count, dtype: int64


<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   v1      5572 non-null   str
 1   v2      5572 non-null   str
dtypes: str(2)
memory usage: 541.4 KB
None


          v1                      v2
count   5572                    5572
unique     2                    5169
top      ham  Sorry, I'll call later
freq    4825                      30

In [ ]:
	# Data for labels
	new_labels = {
	    'spam': 1,
	    'ham': 0
	}
	
	# Encode labels
	df['Labels'] = df['Labels'].map(new_labels)
	
	# Check the data
	df.head()

   v1                                                 v2
0   0  Go until jurong point, crazy.. Available only ...
1   0                      Ok lar... Joking wif u oni...
2   1  Free entry in 2 a wkly comp to win FA Cup fina...
3   0  U dun say so early hor... U c already then say...
4   0  Nah I don't think he goes to usf, he lives aro...

In [ ]:
	X = df['SMS'].to_numpy(dtype=str)
	y = df['Labels'].to_numpy()

Step 3 - Feature Extraction

In [ ]:
	from sklearn.model_selection import train_test_split
	from sklearn.feature_extraction.text import CountVectorizer
	
	# Split training and testing data
	X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)
	
	# Initialize CountVectorizer
	bow = CountVectorizer()
	
	# Fit and transform X_train with CountVectorizer
	X_train = bow.fit_transform(X_train)
	
	# Transform X_test
	# Why only transform? The same reason as in experiment 3
	# We do not want the model to know the parameters used by CountVectorizer to fit X_train
	# Thus, the testing data can remain unfamiliar to the model later
	X_test = bow.transform(X_test)

Step 4 - Model Training and Evaluation

In [ ]:
	from sklearn.naive_bayes import MultinomialNB
	from sklearn.metrics import accuracy_score
	
	# Initialize MultinomialNB
	mnb = MultinomialNB()
	
	# Fit the model
	mnb.fit(X_train, y_train)
	
	# Predict on the training data
	y_pred_train = mnb.predict(X_train)
	
	# Evaluate training accuracy
	acc_train = accuracy_score(y_train, y_pred_train)
	
	# Predict on the training data
	y_pred_test = mnb.predict(X_test)
	
	# Evaluate training accuracy
	acc_test = accuracy_score(y_test, y_pred_test)
	
	# Print evaluation results
	print(f'Training data accuracy: {acc_train}')
	print(f'Test data accuracy: {acc_test}')py